"""
Pydantic schemas for VC-Stack v2 API endpoints
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime


# ============================================================================
# Deal Schemas
# ============================================================================

class DealCreate(BaseModel):
    """Schema for creating a new deal"""
    name: str = Field(..., min_length=1, max_length=255, description="Deal name")
    source: Optional[str] = Field(None, max_length=255, description="How the deal was sourced")
    owner: Optional[str] = Field(None, max_length=100, description="Deal owner/analyst")
    sector: Optional[str] = Field(None, max_length=100, description="Industry sector")
    stage: Optional[str] = Field(None, max_length=100, description="Investment stage")
    status: Optional[str] = Field("active", max_length=50, description="Deal status")


class DealRead(BaseModel):
    """Schema for reading deal data"""
    id: int
    name: str
    source: Optional[str]
    owner: Optional[str]
    sector: Optional[str]
    stage: Optional[str]
    status: str
    created_at: datetime

    class Config:
        from_attributes = True


# ============================================================================
# Memo Schemas
# ============================================================================

class MemoCreate(BaseModel):
    """Schema for creating a memo"""
    deal_id: int = Field(..., description="ID of the deal this memo belongs to")
    memo_type: str = Field(..., max_length=50, description="Type of memo: screening, ic, diligence")
    version: Optional[int] = Field(1, description="Memo version number")
    json_payload: Optional[str] = Field(None, description="JSON content of the memo")
    generated_by_agent: Optional[bool] = Field(True, description="Whether generated by AI agent")
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Confidence score 0-1")


class MemoRead(BaseModel):
    """Schema for reading memo data"""
    id: int
    deal_id: int
    memo_type: str
    version: int
    json_payload: Optional[str]
    generated_by_agent: bool
    confidence_score: Optional[float]
    created_at: datetime

    class Config:
        from_attributes = True


# ============================================================================
# Risk Schemas
# ============================================================================

class RiskCreate(BaseModel):
    """Schema for creating a risk"""
    deal_id: int = Field(..., description="ID of the deal this risk belongs to")
    risk_type: Optional[str] = Field(None, max_length=100, description="Type of risk")
    description: str = Field(..., min_length=1, description="Risk description")
    severity: Optional[str] = Field(None, max_length=20, description="Risk severity: low, medium, high, critical")
    mitigation: Optional[str] = Field(None, description="Mitigation strategy")


class RiskRead(BaseModel):
    """Schema for reading risk data"""
    id: int
    deal_id: int
    risk_type: Optional[str]
    description: str
    severity: Optional[str]
    mitigation: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True


# ============================================================================
# Decision Schemas
# ============================================================================

class DecisionCreate(BaseModel):
    """Schema for creating a decision"""
    deal_id: int = Field(..., description="ID of the deal this decision belongs to")
    verdict: str = Field(..., max_length=50, description="Decision verdict: proceed, hold, pass")
    rationale: Optional[str] = Field(None, description="Decision rationale")
    conditions: Optional[str] = Field(None, description="Conditions for proceeding")


class DecisionRead(BaseModel):
    """Schema for reading decision data"""
    id: int
    deal_id: int
    verdict: str
    rationale: Optional[str]
    conditions: Optional[str]
    decided_at: datetime

    class Config:
        from_attributes = True


# ============================================================================
# Data Room Document Schemas
# ============================================================================

class DataRoomDocumentCreate(BaseModel):
    """Schema for creating a data room document"""
    deal_id: int = Field(..., description="ID of the deal this document belongs to")
    filename: str = Field(..., min_length=1, max_length=255, description="Document filename")
    doc_type: Optional[str] = Field(None, max_length=50, description="Document type: pdf, md, txt, excel, etc.")
    source: Optional[str] = Field("company", max_length=100, description="Document source")
    embedding_id: Optional[str] = Field(None, max_length=255, description="Reference to embedding/chunk ID")


class DataRoomDocumentRead(BaseModel):
    """Schema for reading data room document data"""
    id: int
    deal_id: int
    filename: str
    doc_type: Optional[str]
    source: str
    embedding_id: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True


# ============================================================================
# External Source Schemas
# ============================================================================

class ExternalSourceCreate(BaseModel):
    """Schema for creating an external source"""
    deal_id: int = Field(..., description="ID of the deal this source belongs to")
    url: str = Field(..., min_length=1, max_length=500, description="Source URL")
    source_type: Optional[str] = Field(None, max_length=50, description="Source type: report, news, academic, database, other")
    embedding_id: Optional[str] = Field(None, max_length=255, description="Embedding ID (set after ingestion)")


class ExternalSourceRead(BaseModel):
    """Schema for reading external source data"""
    id: int
    deal_id: int
    url: str
    source_type: Optional[str]
    embedding_id: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True


# ============================================================================
# Research Finding Schemas
# ============================================================================

class ResearchFindingCreate(BaseModel):
    """Schema for creating a research finding"""
    deal_id: int = Field(..., description="ID of the deal this finding belongs to")
    category: Optional[str] = Field(None, max_length=100, description="Finding category: facts, metrics, market, competition, etc.")
    source_type: Optional[str] = Field(None, max_length=50, description="Source type: data_room, external, agent_analysis")
    content: str = Field(..., min_length=1, description="The finding content")
    citation: Optional[str] = Field(None, max_length=500, description="Source citation (URL or document reference)")


class ResearchFindingRead(BaseModel):
    """Schema for reading research finding data"""
    id: int
    deal_id: int
    category: Optional[str]
    source_type: Optional[str]
    content: str
    citation: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True
